name: acme_corp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.4.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  flutter:
    sdk: flutter

  provider: ^6.0.5
  path_provider: ^2.0.2
  path_provider_android: ^2.0.24
  path_provider_ios: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Hive database generators
  build_runner: any
 

flutter:
  uses-material-design: true
  fonts:
    - family: LiberationMono
      fonts:
      - asset: assets/fonts/LiberationMono-Regular.ttf
